### ISSUE TITLE
while installing i get this error please help

### ISSUE THREAD

**Issue by jsathu07** [PayHereLK/payhere-mobilesdk-reactnative#8] opened 2021-07-18 13:13 UTC
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: educhange@0.2.0
npm ERR! Found: react@17.0.1
npm ERR! node_modules/react
npm ERR!   react@"17.0.1" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer react@"^16.8.1" from @payhere/payhere-mobilesdk-reactnative@1.0.11
npm ERR! node_modules/@payhere/payhere-mobilesdk-reactnative
npm ERR!   @payhere/payhere-mobilesdk-reactnative@"1.0.11" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 
npm ERR! See /home/jsathu/.npm/eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/jsathu/.npm/_logs/2021-07-18T13_12_42_940Z-debug.log

**Comment by PayHereDevs** [comment] 2021-07-19 12:18
Hello @jsathu07,

Thank you for pointing out this issue.

This issue was caused by the updates to React and NPM, along with the version constraints that were previously setup by the PayHere React Native SDK. We have allowed all future versions of React Native. 

Incorporating these changes, a new version has been released. Please use the following version in your `package.json` file going forward.

```json
{
  "dependencies": {
    "@payhere/payhere-mobilesdk-reactnative": "1.2.0"
  }
}
```

Do not forget to run these commands after the changes are done.
```
npm install
react-native link @payhere/payhere-mobilesdk-reactnative`
```

If you experience any issues, please let us know. We will be glad to be of support. We will shortly be closing this issue. Further, we have also received your email at the TechSupport email. We will be responding the same.

Thank you again for bringing this issue to our attention.

**Comment by jsathu07** [comment] 2021-07-19 12:31
Thank you for your support

**Closed as completed** 2021-07-22 07:58 UTC
